version: '3'

services:
  analytics-backend:
    build: .
    image: analytics-backend
    restart: always
    environment:
      RELOAD: 'False'
      POSTGRES_ECHO: 'False'
      POSTGRES_DSN: postgresql://anl:example@analytics-portgres:5432/anl
    ports:
      - 4100:4000

  analytics-portgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: anl
      POSTGRES_USER: anl
      POSTGRES_PASSWORD: example
    volumes:
      - /opt/anl/postgresql:/var/lib/psql/data
